### PR TITLE
Upgrade through2 (major).

### PR DESCRIPTION
**Pull request by millette**

### CODE REVIEW

**Comment by millette** [comment]
Same thing here, I ran the tests locally and it was working fine. I'll try to get details about the travis failure.

**Comment by millette** [comment]
The through2 module doesn't define a node engine version, but since [node 6 is going out of maintenance in April](https://github.com/nodejs/Release#lts_schedule), that leaves node 8 as a good option.

I'm using your module with my two patches (upgrades) and it's working fine (on node 10).

**Comment by almost** [comment]
Node 8 seems reasonable as the new lowest supported version

**Comment by almost** [comment]
Thank you! I'm going to merge now!

**Pull request merged**
