### PR TITLE
Fix vulnerabilities; upgrade to mocha 5.

### PR DESCRIPTION
**Pull request by millette**

### CODE REVIEW

**Comment by almost** [comment]
Hi! Thanks for the PR. But to merge this we'd need to get the tests working with Mocha 5.

**Comment by millette** [comment]
Hmm, weird since the tests were completing without error locally. I'll investigate.

**Comment by millette** [comment]
Ah, https://github.com/almost/through2-concurrent/blob/master/.travis.yml is a wee bit old. Mocha 5 requires node 4 or later.

**Comment by millette** [comment]
Hello @almost, just a friendly reminder :-)

**Comment by almost** [comment]
Sorry I thought I'd merged!

**Pull request merged**
